const education = [
  {
    title: "Bachelor of Computer Science",
    place: "University of Wollongong",
    dates: "Jan 2021 - May 2024",
    detail: "Major in Software Engineering and Cybersecurity",
  },
  {
    title: "Masters of Computer Science (Cybersecurity)",
    place: "University of Wollongong",
    dates: "Mar 2025 - Present",
  },
];

const certifications = [
  {
    title: "AWS Academy Cloud Foundations",
    issuer: "AWS Academy",
  },
];

const allWork = [
  {
    title: "Bunkerify",
    slug: "bunkerify",
    category: "Cybersecurity Platform",
    website: "https://www.bunkerify.com",
    techStack: [
      "Next.js",
      "Supabase",
      "Vercel",
      "SendGrid",
      "Tailwind CSS",
      "Web Vulnerability Scanner",
    ],
    points: [
      "Built and deployed Bunkerify on Vercel using Next.js, Supabase (PostgreSQL + auth), and SendGrid for transactional email delivery.",
      "Designed a custom scoring engine from scratch mapping 19 assessment questions to ACSC Essential Eight categories with weighted Maturity Level 0-3 calculations per category.",
      "Implemented automated HTML email reports triggered on assessment completion, delivering personalised risk breakdowns and CTAs.",
      "Integrated Calendly booking workflow to convert assessment completions into consultations.",
      "Deployed a live marketing funnel with a landing page and LinkedIn launch assets to drive inbound leads.",
      "Integrated a live web vulnerability scanner into the results page — triggered after the Essential Eight assessment, with findings stored in Supabase and included in the HTML email report.",
      "Implemented an email gate for new users prior to scanning, with direct scan access for returning authenticated users.",
    ],
  },
  {
    title: "Job Application Assistant",
    slug: "job-application-assistant",
    category: "Web App",
    repo: "https://github.com/mobeen786822/job-application-assistant",
    techStack: [
      "Python",
      "Flask",
      "Flask-Session",
      "Supabase",
      "Anthropic API",
      "OpenAI API",
      "GitHub Actions",
    ],
    points: [
      "Built a web app that tailors resumes from job descriptions and exports PDF/HTML.",
      "Implemented OpenAI-powered content tailoring with strict no-fabrication rules.",
      "Added private access via VPN-only deployment (Tailscale) on a cloud VM.",
      "Added UI preview, download actions, and loading feedback.",
      "Built a GitHub Actions CI/CD security pipeline using Bandit, Semgrep, Gitleaks, and pip-audit.",
      "Identified and resolved a medium-severity Bandit finding related to an interface binding vulnerability.",
      "Extended into a multi-user SaaS with Supabase Auth, server-side sessions, and a per-user dashboard tracking generation history",
      "Implemented server-side monthly usage limits (10/month per user) with Supabase RLS-enforced data isolation.",
    ],
  },
  {
    title: "Local LLM Benchmark — Ollama",
    slug: "local-llm-benchmark",
    category: "AI Engineering",
    repo: "https://github.com/mobeen786822/local-llm-benchmark",
    techStack: [
      "Python",
      "Ollama",
      "Llama 3.2",
      "Phi-3 Mini",
      "Gemma 2",
      "Ubuntu",
    ],
    points: [
      "Benchmarked Llama 3.2, Phi-3 Mini, and Gemma 2 running entirely offline via Ollama on a CPU-only Ubuntu VM across 4 task types — documenting speed, reliability, and quality tradeoffs for local inference.",
      "Identified task-specific failure modes including timeouts that would not surface in quality-only evaluations.",
      "Designed a Python benchmarking script evaluating all 3 models across 4 task types (summarisation, JSON extraction, code generation, and multi-step reasoning) — 12 data points total.",
      "Documented speed vs quality tradeoffs: Gemma 2 fastest at 4.8 tok/s, Llama 3.2 most reliable (4/4 tasks), Phi-3 Mini best code quality but unreliable on structured output.",
    ],
  },
  {
    title: "Cyber Content Bot",
    slug: "cyber-content-bot",
    category: "AI Engineering",
    repo: "https://github.com/mobeen786822/cyber-content-bot",
    website: "https://cyber-content-bot-ui.onrender.com",
    techStack: [
      "Python",
      "Flask",
      "React",
      "TypeScript",
      "Vite",
      "Tailwind CSS",
      "Anthropic Claude API",
    ],
    points: [
      "An automated cybersecurity content pipeline that aggregates HIGH/CRITICAL CVEs from NVD, actively exploited vulnerabilities from CISA KEV, and AI security research from arXiv - then uses Claude Haiku to draft LinkedIn posts for weekly review. Features tone control, on-demand triggering, and a React/TypeScript dashboard.",
      "Aggregates data from three sources concurrently — NVD API (CVSS ≥ 7.0), CISA Known Exploited Vulnerabilities feed, and arXiv AI security papers — filtered to the past 7 days.",
      "Supports three generation tones (professional, conversational, technical) with one-click regeneration using the same fetched data.",
      "Resolved 6 CVEs in dependencies (Flask, Flask-CORS, Requests) and a HIGH severity Bandit B201 finding surfaced by the CI/CD security pipeline.",
    ],
  },
  {
    title: "LLM Security Tester",
    slug: "llm-security-tester",
    category: "AppSec",
    repo: "https://github.com/mobeen786822/-llm-security-tester",
    techStack: [
      "Python",
      "Flask",
      "React",
      "Vite",
      "Tailwind CSS",
      "Ollama",
      "Anthropic API",
    ],
    points: [
      "A full-stack tool that probes LLMs for prompt injection, jailbreaking, system prompt extraction, data exfiltration, and role confusion attacks across 15 test cases.",
      "Compared Llama 3.2 vs Claude Haiku - Llama achieved 15/15 resistant while Haiku returned 3 failures and 5 partials on HIGH severity attacks.",
      "Built a React/Tailwind dashboard with per-category breakdowns, severity badges, expandable prompt/response rows, and JSON report export.",
      "Designed an extensible JSON attack library so new test cases and categories can be added without modifying backend or frontend code.",
    ],
  },
  {
    title: "Web Vulnerability Scanner",
    slug: "web-vulnerability-scanner",
    category: "AppSec",
    website: "https://web-vulnerability-scanner-lqy5.onrender.com/",
    techStack: [
      "Python",
      "Flask",
      "React",
      "Vite",
      "Tailwind CSS",
      "GitHub Actions",
    ],
    points: [
      "A full-stack web vulnerability scanner with 6 scanner modules covering security headers, SSL/TLS, sensitive path exposure, cookie flags, open redirects, and information disclosure. Supports single and batch URL scanning with concurrent execution, a severity-coded React dashboard, and client-side JSON report export.",
      "Implements concurrent URL scanning via ThreadPoolExecutor with a shared requests.Session per URL for efficiency — supports single and batch scan modes.",
      "Each finding includes a severity rating (CRITICAL/HIGH/MEDIUM/LOW/INFO), status badge, detail, and remediation recommendation.",
      "CI/CD security pipeline with Bandit SAST, Gitleaks secrets detection, and pip-audit dependency scanning with fail-gate on HIGH findings.",
    ],
  },
  {
    title: "Production Support Incident Console",
    slug: "incident-console",
    category: "Operations Simulation",
    repo: "https://github.com/mobeen786822/Production-Support-Incident-Console",
    website: "https://incident-console-ui.onrender.com/",
    techStack: [
      "React",
      "TypeScript",
      "FastAPI",
      "Python",
      "SQLAlchemy",
      "Docker",
      "JWT",
      "GitHub Actions",
    ],
    points: [
      "Built a web-based incident management console to simulate production support workflows end-to-end.",
      "Implemented incident lifecycle tracking with severity, status transitions, ownership, and event timelines.",
      "Added SLA-aware monitoring with breach indicators to support prioritisation and response quality.",
      "Implemented runbook and root-cause analysis capture to improve incident resolution consistency.",
      "Implemented a full-stack security pipeline across Python (Bandit, pip-audit) and JavaScript (npm audit, Gitleaks).",
      "Discovered and resolved 8 CVEs in backend dependencies through targeted remediation and dependency upgrades.",
      "Replaced python-jose with PyJWT due to an unresolvable vulnerability chain and migrated the authentication implementation.",
      "Resolved a high-severity frontend vulnerability by upgrading affected dependencies.",
    ],
  },
  {
    title: "Golden Hour Pilates Website Redesign",
    slug: "golden-hour-pilates",
    category: "Client Website and Production Launch",
    website: "https://www.goldenhourpilates.com.au",
    techStack: [
      "React",
      "Vite",
      "JavaScript",
      "CSS",
      "Booking integration",
      "Vercel",
      "Accessibility",
      "Local SEO",
    ],
    points: [
      "Audited the existing Squarespace homepage and translated its strong identity into a clearer, conversion-focused customer journey.",
      "Rebuilt and launched the production website as a responsive React application using the studio's official identity, photography, and integrated class schedule.",
      "Strengthened the introductory-offer journey with clearer calls to action, persistent mobile booking access, class discovery, beginner guidance, FAQs, and direct contact actions.",
      "Implemented semantic structure, reduced-motion support, keyboard focus states, local-business metadata, responsive QA, and a production Vercel deployment.",
    ],
  },
  {
    title: "JZ Tech Web Studio",
    slug: "jz-tech",
    category: "Business Website and Brand System",
    website: "https://www.jztech.com.au",
    techStack: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Vercel",
      "GitHub Actions",
      "Accessibility",
      "Technical SEO",
    ],
    points: [
      "Designed and launched a production website for an Australian web studio, translating its brand foundation into a distinctive dark editorial interface.",
      "Structured the customer journey around services, delivery process, maintenance, proof, FAQs, and a direct enquiry path.",
      "Implemented a responsive cinematic hero with poster, mobile, reduced-motion, and data-saving fallbacks.",
      "Built portable brand tokens, automated WCAG contrast checks, semantic metadata, structured data, CI validation, and a production Vercel deployment.",
    ],
  },
  {
    title: "JZ Supports & Maintenance Website",
    slug: "jzsm",
    category: "Multi-page Service Website",
    website: "https://www.jzsm.com.au",
    techStack: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Relume",
      "shadcn/ui",
      "Radix UI",
      "Vercel",
      "Accessibility",
    ],
    points: [
      "Designed and launched a seven-route website for a practical support and home-maintenance provider.",
      "Built distinct service journeys for NDIS supports, injury recovery, cleaning, lawns and maintenance, company information, and enquiries.",
      "Adapted genuine Relume components into an editable local component system using shadcn/Radix foundations and project-specific design tokens.",
      "Implemented accessible navigation, motion safeguards, funding disclaimers, semantic metadata, responsive QA, and production Vercel hosting.",
    ],
  },
  {
    title: "Cancer Awareness Mobile App",
    slug: "cancer-awareness-app",
    category: "Mobile App",
    repoNote: "Private repo - available on request.",
    techStack: ["React Native", "TypeScript", "Firebase"],
    points: [
      "Built a cross-platform mobile app using React Native and TypeScript.",
      "Implemented Firebase integration for authentication, cloud data storage, and messaging workflows.",
      "Added geolocation and media upload capabilities with structured in-app navigation.",
      "Built educational and awareness-focused user journeys with clear call-to-action screens and reminders.",
      "Focused on privacy-conscious data handling for sensitive health-related user interactions.",
    ],
  },
];

const volunteer = [
  {
    title: "Web Developer (catchadrive.com)",
    org: "Catch a Drive",
    dates: "Nov 2025 - Jan 2026",
    points: [
      "Delivered front-end and back-end features for the Catch a Drive platform across booking and user-flow pages.",
      "Built responsive UI components for mobile and desktop to improve navigation clarity and completion flow.",
      "Integrated API-backed functionality for dynamic content and user actions, reducing manual content handling.",
    ],
  },
  {
    title: "Web Developer (Hentley.co)",
    org: "Hentley",
    dates: "Jan 2018 - Mar 2019",
    points: [
      "Implemented custom storefront components to improve product discovery and shopper navigation.",
      "Supported server-side functionality for product rendering, checkout-adjacent workflows, and content updates.",
      "Refined responsive layouts and styling to maintain consistent UX across mobile, tablet, and desktop.",
    ],
  },
];

const skillCategories = [
  {
    name: "Core Engineering",
    items: [
      "React",
      "TypeScript",
      "Vite",
      "Tailwind CSS",
      "React Native",
      "Next.js",
      "JavaScript",
      "Node.js",
      "Flask",
      "FastAPI",
      "Docker",
      "Supabase",
      "SQLAlchemy",
      "Nginx",
      "Firebase",
      "REST API Integration",
      "Jest",
      "React Testing Library",
      "Cybersecurity",
      "Networking",
      "SQL",
      "NoSQL",
      "Python",
      "Java",
      "C++",
    ],
  },
  {
    name: "DevSecOps",
    items: [
      "GitHub Actions",
      "Bandit",
      "Semgrep",
      "Gitleaks",
      "pip-audit",
      "npm audit",
      "SAST",
      "dependency scanning",
      "secrets detection",
    ],
  },
];

const cybersecurityTools = [
  "Kali Linux",
  "Nmap",
  "Metasploit",
  "Wireshark",
  "Burp Suite",
  "Penetration Testing",
  "Vulnerability Assessment",
  "Incident Response",
  "Threat Intelligence",
  "Network Segmentation",
  "Log Analysis",
  "Firewall Configuration",
];

export {
  education,
  certifications,
  allWork,
  volunteer,
  skillCategories,
  cybersecurityTools,
};
